<Project>
  <PropertyGroup>
    <Authors>hawkinslabdev</Authors>
    <Product>Warden</Product>
    <PackageProjectUrl>https://github.com/hawkinslabdev/warden</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hawkinslabdev/warden</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
